my_file = open('test_5.2.txt', 'r')
log = my_file.read()
print(f'Содержимое файла: \n {log}')
my_file = open('test_5.2.txt', 'r')
log = my_file.readlines()
print(f'Количество строк в файле - {len(log)}')
my_file = open('test_5.2.txt', 'r')
log = my_file.readlines()
for i in range(len(log)):
    print(f'Окличество символов {i + 1} - ой строки {len(log[i])}')
my_file = open('test_5.2.txt', 'r')
log = my_file.read()
log = log.split()
print(f'Общее количество слов - {len(log)}')
my_file.close()
